### ISSUE TITLE
PHP Fatal error:  Uncaught mysqli_sql_exception

### ISSUE THREAD

**Issue by lucize** [bcombs18/osTicket-Inventory-Manager#41]
I want to try this plug in but it seems that I get this error

`Fatal error: Uncaught mysqli_sql_exception: Unknown column 'A1.host_name' in 'order clause' in /home/support/upload/include/mysqli.php:189 Stack trace: #0 /home/support/upload/include/mysqli.php(189): mysqli->query() #1 /home/support/upload/include/class.orm.php(3470): db_query() #2 /home/support/upload/include/class.orm.php(3517): MySqlExecutor->execute() #3 /home/support/upload/include/class.orm.php(2097): MySqlExecutor->getArray() #4 /home/support/upload/include/class.orm.php(2047): HashArrayIterator->{closure}() #5 /home/support/upload/include/class.orm.php(2026): CallbackSimpleIterator->next() #6 /home/support/upload/include/class.orm.php(2035): CallbackSimpleIterator->rewind() #7 /home/support/upload/include/class.orm.php(1706): CallbackSimpleIterator->valid() #8 /home/support/upload/include/class.orm.php(1741): CachedResultSet->fillTo() #9 /home/support/upload/include/class.orm.php(1602): CachedResultSet->offsetGet() #10 /home/support/upload/include/class.orm.php(1458): QuerySet->offsetGet() #11 /home/support/upload/include/plugins/osTicket-Inventory-Manager-1.0.1/views/queue-assets.tmpl.php(212): QuerySet->exists() #12 /home/support/upload/include/plugins/osTicket-Inventory-Manager-1.0.1/include/model/assets.php(242): require('...') #13 /home/support/upload/include/plugins/osTicket-Inventory-Manager-1.0.1/include/controller/Asset.php(190): require_once('...') #14 /home/support/upload/include/class.dispatcher.php(145): controller\Asset->handle() #15 /home/support/upload/include/class.dispatcher.php(38): UrlMatcher->dispatch() #16 /home/support/upload/include/class.dispatcher.php(120): Dispatcher->resolve() #17 /home/support/upload/include/class.dispatcher.php(38): UrlMatcher->dispatch() #18 /home/support/upload/scp/dispatcher.php(45): Dispatcher->resolve() #19 {main} thrown in /home/support/upload/include/mysqli.php on line 189
`

and some part of the personal queue are displayed in the page

osticket 1.16.3
php 8.1
ubuntu 20.4

**Comment by bcombs18** [comment]
Hi @lucize, Sorry for the delay in response. Can you provide some more information about what is going on, maybe some screenshots of the page? What are the steps that seem to generate the error?

**Comment by lucize** [comment]
@bcombs18 sorry, I was away, it seems that it didn't work for me
I removed 1.0.1 and copied 1.0.3. I also use the multi ldap plugin and we have setup custom queue
seems that the custom queue is displayed in the inventory page

![image](https://user-images.githubusercontent.com/6313831/177880983-f157d1f1-6511-41c3-9a0b-217785e7d633.png)

**Comment by bcombs18** [comment]
@

**Comment by bcombs18** [comment]
@lucize Sorry, I didn't see this until now. This issue has since been resolved with the most recent release, v1.1.1. Try installing that and let me know if you have any issues. I think most of the bugs with the plugin have been squashed at this point.

**Comment by lucize** [comment]
@bcombs18 sorry for such late reply, updated to latest release and I have this, do you think that custom queues affect this ?

![image](https://user-images.githubusercontent.com/6313831/227032597-e1e0df42-c247-4d01-99d0-678ae539f03f.png)

**Comment by bcombs18** [comment]
@lucize What web server are you running? Also, which version of osTicket are you using?

**Comment by lucize** [comment]
Server version: Apache/2.4.56 (Ubuntu)
osTicket 1.16.3
